baseURL = '/'
languageCode = 'zh-cn'
title = '香草山书架'
theme = 'my-book'

[params]
  BookTheme = 'light'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
  