baseURL = '/'
languageCode = 'zh-cn'
hasCJKLanguage = true
defaultContentLanguage = 'zh'
title = 'é¦™è‰å±±'
theme = 'my-book'

[[menu.before]]
  name = "ğŸ“– ä¹¦æ¶"
  pageRef = "/books"
  weight = 1

[[menu.before]]
  name = "ğŸ¼ éŸ³ä¹"
  pageRef = "/music"
  weight = 2

[[menu.before]]
  name = "ğŸ§’ å„¿ç«¥"
  pageRef = "/children"
  weight = 3

[params]
  BookTheme = 'light'
  BookSearch = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
  